namespace Convai.Domain.Identity
{
    /// <summary>
    ///     Provides an application-specific end user identifier for Convai connections.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         Implementations of this interface generate stable identifiers that allow the Convai server
    ///         to track end users across sessions. This enables features such as:
    ///     </para>
    ///     <list type="bullet">
    ///         <item>
    ///             <description>Long-Term Memory (LTM) - Characters remember previous conversations</description>
    ///         </item>
    ///         <item>
    ///             <description>Monthly Active User (MAU) tracking for billing</description>
    ///         </item>
    ///         <item>
    ///             <description>Cross-session conversation continuity</description>
    ///         </item>
    ///     </list>
    ///     <para>
    ///         <b>Important - Identity Flow:</b>
    ///     </para>
    ///     <para>
    ///         The <c>end_user_id</c> generated by this provider is sent to the server during connection.
    ///         The server creates or resolves a Speaker record and includes the resulting <c>speaker_id</c>
    ///         (UUID) in connection metadata.
    ///     </para>
    ///     <para>
    ///         The mapping is: <c>end_user_id</c> (SDK-provided) → <c>speaker_id</c> (server-generated UUID)
    ///     </para>
    ///     <para>
    ///         The server-generated <c>speaker_id</c> is used for:
    ///     </para>
    ///     <list type="bullet">
    ///         <item>
    ///             <description>Long-Term Memory (Mem0) with key format: <c>speaker_id:character_id</c></description>
    ///         </item>
    ///         <item>
    ///             <description>Interaction persistence in the database</description>
    ///         </item>
    ///         <item>
    ///             <description>Transcript attribution in multi-user scenarios</description>
    ///         </item>
    ///     </list>
    ///     <para>
    ///         The default implementation, <c>DeviceEndUserIdProvider</c>, uses the device's unique identifier
    ///         with a GUID fallback for platforms where device identification is unavailable.
    ///     </para>
    ///     <para>
    ///         Custom implementations can be registered with the <c>ConvaiServiceLocator</c> to provide
    ///         application-specific user identification (e.g., based on authenticated user accounts).
    ///     </para>
    /// </remarks>
    public interface IEndUserIdProvider
    {
        /// <summary>
        ///     Generates or resolves the end user identifier that should be sent with Convai connect requests.
        /// </summary>
        /// <returns>
        ///     A stable end user identifier string. The identifier should be consistent across sessions
        ///     for the same end user to enable cross-session features.
        /// </returns>
        /// <remarks>
        ///     This value is sent to the server as <c>end_user_id</c> and is used to resolve
        ///     the server-side Speaker record. The server supplies a <c>speaker_id</c> (UUID)
        ///     via connection metadata, which is stored in
        ///     <see cref="Convai.Infrastructure.Networking.IConvaiRoomController.ResolvedSpeakerId" /> when available.
        /// </remarks>
        public string GenerateEndUserId();
    }
}
