using System;
using Convai.RestAPI;
using Convai.RestAPI.Services;
using Convai.Shared.Types;

namespace Convai.Infrastructure.Networking
{
    /// <summary>
    ///     Provides configuration settings for Convai transport connections.
    /// </summary>
    public interface IConfigurationProvider
    {
        /// <summary>
        ///     Gets the API key for authenticating with the Convai service.
        /// </summary>
        public string ApiKey { get; }

        /// <summary>
        ///     Gets the base URL of the Convai core server (without endpoint path).
        ///     Example: "https://live.convai.com"
        /// </summary>
        public string CoreServerUrl { get; }

        /// <summary>
        ///     Gets the connection type for character sessions.
        /// </summary>
        public ConvaiConnectionType ConnectionType { get; }

        /// <summary>
        ///     Gets the video track name used for vision streaming.
        /// </summary>
        public string VideoTrackName { get; }

        /// <summary>
        ///     Gets the LLM provider for character responses.
        /// </summary>
        public ConvaiLLMProvider LlmProvider { get; }

        /// <summary>
        ///     Gets the server endpoint for room connections.
        /// </summary>
        public ConvaiServerEndpoint ServerEndpoint { get; }

        /// <summary>
        ///     Gets the lip sync transport options negotiated for this room session.
        ///     Defaults to <see cref="LipSyncTransportOptions.Disabled" /> when no lip sync capability is present.
        /// </summary>
        public LipSyncTransportOptions LipSyncTransportOptions { get; }

        /// <summary>
        ///     Gets the end user identifier for cross-session tracking.
        /// </summary>
        /// <remarks>
        ///     This identifier enables features like Long-Term Memory (LTM) and Monthly Active User (MAU) tracking.
        ///     The value is typically generated by an <see cref="Convai.Domain.Identity.IEndUserIdProvider" /> implementation.
        /// </remarks>
        public string EndUserId { get; }

        /// <summary>
        ///     Stores a character session ID for session resume functionality.
        /// </summary>
        /// <param name="characterId">The character's unique identifier.</param>
        /// <param name="sessionId">The session ID to store.</param>
        public void StoreCharacterSessionId(string characterId, string sessionId);

        /// <summary>
        ///     Retrieves a stored character session ID.
        /// </summary>
        /// <param name="characterId">The character's unique identifier.</param>
        /// <returns>The stored session ID, or null if not found.</returns>
        public string GetCharacterSessionId(string characterId);

        /// <summary>
        ///     Clears the stored session ID for a specific character.
        /// </summary>
        /// <param name="characterId">The character's unique identifier.</param>
        public void ClearCharacterSessionId(string characterId);

        /// <summary>
        ///     Clears all stored character session IDs.
        /// </summary>
        public void ClearAllCharacterSessionIds();
    }

    internal static class RoomConnectionRequestLipSyncMapper
    {
        internal static void Apply(RoomConnectionRequest roomRequest, in LipSyncTransportOptions options)
        {
            if (roomRequest == null) throw new ArgumentNullException(nameof(roomRequest));

            if (!options.IsValid)
            {
                roomRequest.BlendshapeProvider = null;
                roomRequest.BlendshapeConfig = null;
                return;
            }

            roomRequest.BlendshapeProvider = options.Provider;
            roomRequest.BlendshapeConfig = new ConvaiBlendshapeConfig(
                options.EnableChunking,
                options.ChunkSize,
                options.OutputFps,
                options.Format,
                options.FramesBufferDuration);
        }
    }
}
